### PR TITLE
Create Strings.nl_nl.json

### PR DESCRIPTION
**Pull request by Stephan-P**
Dutch translation

### CODE REVIEW

**Comment by Stephan-P** [comment]
Could you explain the meaning and use case of line 150: "Command_Name_SameNumberCount": "Numbers to same count",
I'm having a hard time understanding what it's for. I also took the Korean (I presume original) text and fed this into Google translate, but still I could not understand what it's about.

**Comment by daramkun** [comment]
I tried explain but it is so difficult...

Example) `FileName_001.png`, `FileName_02.png` files processing to `Numbers to same count` with argument `3`, Result is `FileName_001.png`, `FileName_002.png`. argument `4`, Result is `FileName_0001.png`, `FileName_0002.png`

**Comment by Stephan-P** [comment]
Aha, I get it.
So we are talking about a fixed amount of digits.
Would "Digits:" work?
I was briefly considering "Numvber of digits:" as well, but then we enter into the confusion of THIS number of digits and the numbering that we want to include into the new filenames. So just "Digits:" is probably best.

**Comment by Stephan-P** [comment]
I was a little bit too fast, as I now notice that the function is also about FIXING the amount of digits.
To include this,  "Fix amount of digits" covers the function more precisely.

**Pull request merged**
